name: Automatic tests, code-coverage and auto-deployment files upload to S3
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Add S3 bucket name and aws keys to tests config file
        run: |
          sed -i 's/S3_BUCKET_NAME/${{ secrets.AWS_S3_BUCKET_TEST }}/g' tests/config.yaml
          sed -i 's/ACCESS_KEY_ID/${{ secrets.AWS_ACCESS_KEY_ID }}/g' tests/config.yaml
          sed -i 's/SECRET_ACCESS_KEY/${{ secrets.AWS_SECRET_ACCESS_KEY }}/g' tests/config.yaml

          cat tests/config.yaml
      - name: Run unit tests
        run: |
          pip install pytest
          pip install boto3
          pip install httpretty
          pip install pyyaml
          pytest tests/lambda_test.py
      - name: Create 'upload' directory
        run: |
          mkdir -p upload
      - name: Rename 'src' directory to 'app'
        run: |
          mv src app
      - name: Zip 'app' directory into 'upload' directory
        run: |
          zip -r upload/lambda_function_code.zip app
      - name: Copy 'auto-deployment.yaml' to 'upload' directory
        run: |
          cp aws/auto-deployment.yaml upload
      - name: Run python script that empty the S3 bucket and upload files to it with public-read
        run: |
          pip install boto3
          python action/run.py
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}