name: Update aws cost and usage auto-deployment files
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create 'upload' directory
        run: |
          mkdir -p ${{ github.workspace }}/upload
      - name: Rename 'src' directory to 'app'
        run: |
          mv ${{ github.workspace }}/src ${{ github.workspace }}/app
      - name: Zip 'app' directory into 'upload' directory
        run: |
          zip -r ${{ github.workspace }}/upload/lambda_function_code.zip ${{ github.workspace }}/app
      - name: Copy 'auto-deployment.yaml' to 'upload' directory
        run: |
          cp ${{ github.workspace }}/aws/auto-deployment.yaml ${{ github.workspace }}/upload
      - uses: awact/s3-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          SOURCE_DIR: ${{ github.workspace }}/upload
          AWS_REGION: 'us-east-1'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}